### ISSUE TITLE
Hiding a long buffer name hides all spaceline segments

### ISSUE THREAD

**Issue by Stebalien** [TheBB/spaceline#147] opened 2017-06-15 17:31 UTC
When a long buffer name segment is hidden, the buffer name segment on all other windows (and all segments after that) are *also* hidden.

Note: This only happens when a long buffer name is hidden. When a short buffer name is hidden, segments in other windows aren't affected.

# Screen Shots

## Before switching to a buffer with a long name

![with-buffer-names](https://user-images.githubusercontent.com/310393/27193944-99a8a834-51b5-11e7-9588-d3eafc809e76.png)

## After switching

![missing-buffer-names](https://user-images.githubusercontent.com/310393/27193943-99a507e2-51b5-11e7-9cc6-73a03278318a.png)

**Comment by deb0ch** [comment] 2017-06-21 08:18
Hum, that needs investigation.

Does it only happen with xwidget / web buffers, or with *any* buffer with a long name ?

**Comment by Stebalien** [comment] 2017-06-21 16:57
Any buffer with a long name. For me, the cutoff is around 60 characters.

**Comment by et2010** [comment] 2017-07-01 02:21
Any updates on this?

**Comment by TheBB** [comment] 2017-07-01 06:11
It should be enough to give the buffer name segment (and other segments that tend to be long) a lower priority, so that it is the first candidate for hiding.

**Comment by TheBB** [comment] 2017-07-01 06:28
I've made an update that changes the priority of this segment. It should be among the first to hide now.

**Comment by et2010** [comment] 2017-07-01 12:17
It works! Thanks for the fix!

**Comment by osv** [comment] 2017-07-03 13:17
How to customize priority for buffer name after 07235fe45569c6fa669ba6426b806b8c81b26d65? I want to see file name as far as possible

**Comment by TheBB** [comment] 2017-07-03 13:19
Hang on, we still haven't decided on what meaning the priority keyword should have.

**Comment by TheBB** [comment] 2017-07-03 13:20
But if you're interested the current version, you can set it to –10 or something similarly low.

**Comment by acowley** [comment] 2017-11-16 19:10
I apologize for this dumb question, but to echo @osv, what is the easiest way to customize the priority of a segment? The `buffer-id` segment begin hidden is a mild nuisance for me, too. It happens to me quite often when switching workspaces on macOS. Deleting other windows (in emacs parlance) brings it back, then I can resplit the frame to get back to the mode line displaying as intended.

**Comment by deb0ch** [comment] 2017-11-16 20:09
@osv @acowley The question isn't dumb.

To set the priorities the way you want you can copy and paste the spaceline definition in [spaceline-config.el](https://github.com/TheBB/spaceline/blob/master/spaceline-config.el). Copy the [spaceline-spacemacs-theme](https://github.com/TheBB/spaceline/blob/master/spaceline-config.el#L64) function if you are using Spacemacs, [spaceline-emacs-theme](https://github.com/TheBB/spaceline/blob/master/spaceline-config.el#L80) if you are using vanilla Emacs (don't forget to copy [spaceline--theme](https://github.com/TheBB/spaceline/blob/master/spaceline-config.el#L26) as well).

Then just rename the functions (or extract the code), modify it and use it from your dotfile.

If you do that keep in mind that the priority sorting algorithm might change in a near future, so you'll have to tweak it of you notice breakings.

By the way, in Spacemacs you can display in the echo area the name of the file the buffer is visiting by pressing `<SPC> f y`.

**Comment by TheBB** [comment] 2018-03-20 08:44
This should be fixed now.

**Closed by TheBB** 2018-03-20 08:44 UTC
