### ISSUE TITLE
Change color of spaceline-highlight-face-modified

### ISSUE THREAD

**Issue by HiCodin** [TheBB/spaceline#37] opened 2015-11-29 03:21 UTC
Is there anyway where i can change the color of highlight modified face ? 
I tried looking in `M-x` - `Customize-Group` - `Spaceline` and it seems that i can't modify there.

**Comment by TheBB** [comment] 2015-11-29 09:20
Yeah I must have done something wrong. You can still change it outside of customize though, in the meantime.

**Comment by HiCodin** [comment] 2015-11-29 14:17
oh ok. can you show me how can I change it outside of customize ? since i am relatively new to emacs and stuffs, i am getting lost. I tried changed the colors directly [here](https://github.com/TheBB/spaceline/blob/master/spaceline.el#L121) but its not taking effect.

**Comment by TheBB** [comment] 2015-11-29 18:11
If I remember correctly it's something like this.

```elisp
(custom-set-faces
 '((spaceline-highlight-face ((t (:foreground "..." :background "..." ...))))))
```

**Comment by TheBB** [comment] 2015-11-29 18:13
I had an extra paren. That should work :point_up: 

http://www.gnu.org/software/emacs/manual/html_node/elisp/Face-Attributes.html  
http://www.gnu.org/software/emacs/manual/html_node/elisp/Defining-Faces.html#Defining-Faces

**Comment by HiCodin** [comment] 2015-11-30 04:25
Its working now. Thank you so much for the help. :+1:

**Comment by TheBB** [comment] 2015-11-30 11:16
If it's all right with you I will keep this open, since the faces *should* be changeable in customize.

**Comment by HiCodin** [comment] 2015-12-01 02:16
sure. people can get an idea from this as well if they want to change colors.

**Comment by HiCodin** [comment] 2015-12-01 04:33
after upgrading to the latest version, i can change the modified/read-only/unmodified faces now in customize. sweet !

**Comment by DougDavenport** [comment] 2016-06-14 12:24
Hope this is a good place to ask...

I'm running spacemacs on linux in a terminal, for me the active window # is a light grey which is difficult to read on an orange background. Is there a way to change the foreground of the active window number?

**Comment by TheBB** [comment] 2016-06-14 12:25
Yeah, you can just set the foreground of the highlight face(s) you're interested in.

**Comment by DougDavenport** [comment] 2016-06-14 18:26
Thanks, I'm new to spacemacs/emacs and here is what worked for me, in dotspacemacs/user-config added:

(setq spaceline-highlight-face-func 'spaceline-highlight-face-evil-state)
(set-face-attribute 'spaceline-evil-normal nil :foreground "black")

The first line actually fixed the problem changing the foreground color to 3e3d31 (was a light grey before).

The second line allowed me to change the foreground but only works if the first line is also run.

Is this the expected behavior?

**Comment by TheBB** [comment] 2016-06-14 18:29
Spacemacs uses its own highlight face function because it has more evil states. If you use Spacemacs you should modify `spacemacs-normal-face` and so on. Spacemacs also has logic which sets the foreground of those faces equal to the background of the mode-line face, which could potentially look silly depending on the theme you are using. To be precise, none of these are Spaceline issues.

**Comment by jsoo1** [comment] 2017-03-21 15:29
This is likely a spacemacs issue, but this is the only issue i can find that relates to my problem.  When using spaceline with spacemacs in terminal the default face has a white foreground.  This renders the face unreadable.  Customize has the correct foreground colors, also.
<img width="571" alt="screen shot 2017-03-21 at 8 27 53 am" src="https://cloud.githubusercontent.com/assets/10039785/24155230/7497e52a-0e10-11e7-99c3-aeb583c3865b.png">

**Comment by jsoo1** [comment] 2017-04-02 19:49
Placing `'(spacemacs-normal-face ((t (:inherit 'mode-line :foreground "#3E3D31" :background "DarkGoldenRod2"))))` in `custom-set-faces` fixes the issue.  Does that mean that somewhere the face is getting clobbered?

**Comment by jbharat** [comment] 2017-08-05 03:13
@jsoo1 facing the same issue.  I placed it in user-config and it didnt work. It works only if it is in custom-set-faces

**Comment by jsoo1** [comment] 2017-08-31 05:02
@jbharat have you had any success with this? I haven't paid much mind to it since I started placing my customize section in a separate file. I would like to know what the issue is and I'm not a customize expert (yet).

**Comment by jbharat** [comment] 2017-09-01 02:03
@jsoo1  Not working yet. But I dont have any issue as such. I wanted to theme it but could not. Thats all

**Comment by jbharat** [comment] 2017-12-21 05:30
@jsoo1  I am able to change the color of evil state in the modeline with the below code. I dont like darkgoldenrod2 color so wanted to set it to a whitish color. 
```
      ;; normal mode cursor color
      (setq evil-normal-state-cursor '((bar . 2) "#E8E4FE"))
      
      (setq spaceline-highlight-face-func 'spaceline-highlight-face-evil-state)
      (set-face-attribute 
       'spaceline-evil-normal nil :background "#E8E4FE" :foreground "black")

```

**Comment by jsoo1** [comment] 2018-06-18 17:22
Thanks @jbharat. Are you using spacemacs? For me the solution was this but the spacemacs face versions:
``` elisp
(set-face-attribute 'spacemacs-normal-face nil :foreground "#262626")
(set-face-attribute 'spacemacs-hybrid-face nil :foreground "#262626")
(set-face-attribute 'spacemacs-emacs-face nil :foreground "#262626")
(set-face-attribute 'spacemacs-evilified-face nil :foreground "#262626")
(set-face-attribute 'spacemacs-visual-face nil :foreground "#262626")
;; ... etc.
```
In light of this, I will instead report upstream.

**Comment by deb0ch** [comment] 2018-11-25 01:37
Closing this as it is apparently not a Spaceline but a Spacemacs issue and was duly reported there, and the initial issue has been fixed.

**Closed by deb0ch** 2018-11-25 01:37 UTC
