### ISSUE TITLE
When using only window-numbering spaceline shows an extra "1"

### ISSUE THREAD

**Issue by jwintz** [TheBB/spaceline#68] opened 2016-03-14 19:40 UTC
Hello,

Thanks for the package. I dunno want to use spacemacs, I however like its look & feel.

When using <code>window-numbering</code>  only, spaceline seems to infer the <code>eyebrowse</code> workspace identifier.

<img width="367" alt="screen shot 2016-03-14 at 20 36 24" src="https://cloud.githubusercontent.com/assets/3277054/13757478/f303fe78-ea24-11e5-8739-8549580781b0.png">

How do I get rid of that ?

Thanks.

**Comment by TheBB** [comment] 2016-03-14 19:44
I can't reproduce this unfortunately. Can you check that calling `(spaceline--segment-workspace-number)` manually returns nil?

**Comment by jwintz** [comment] 2016-03-14 19:54
When adding

<code>
(when (display-graphic-p)
  (load-theme 'spacemacs-dark t)
  (set-face-attribute 'mode-line nil :box nil)
  (setq ns-use-srgb-colorspace nil)
  (require 'spaceline-config)
  (setq powerline-default-separator 'wave)
  (setq spaceline-toggle-window-number-on t)
  (setq spaceline-toggle-workspace-number-on nil)
  (message "%s" spaceline--segment-workspace-number)
  (spaceline-spacemacs-theme)
  (spaceline-helm-mode +1))
</code>

I've got the following error:

<code>
Symbol's value as variable is void: spaceline--segment-workspace-number
</code>

  - ju

**Comment by TheBB** [comment] 2016-03-14 19:57
It's a function, not a variable.

**Comment by TheBB** [comment] 2016-03-14 19:58
Also, you're using the toggles wrong. They are functions too, not variables. If you want to use the variables, they are called `spaceline-<segment>-p`.

**Comment by jwintz** [comment] 2016-03-14 20:03
Ok, I've changed to the following:

<pre>
(when (display-graphic-p)
  (load-theme 'spacemacs-dark t)
  (set-face-attribute 'mode-line nil :box nil)
  (setq ns-use-srgb-colorspace nil)
  (require 'spaceline-config)
  (setq powerline-default-separator 'wave)
  (setq spaceline-toggle-window-number-on-p t)
  (setq spaceline-toggle-workspace-number-on-p nil)
  (spaceline-spacemacs-theme)
  (spaceline-helm-mode +1))
</pre>

However, the error persists. How can I debug this ?

**Comment by jwintz** [comment] 2016-03-14 20:05
Also, <code>helm-mode</code> shows an underline. How can I get rid of it ?

<img width="363" alt="screen shot 2016-03-14 at 21 04 24" src="https://cloud.githubusercontent.com/assets/3277054/13758196/79dbc8ce-ea28-11e5-882c-6b7caab91b15.png">

**Comment by TheBB** [comment] 2016-03-14 20:06
You can try increasing `powerline-scale`.

I repeat:

> I can't reproduce this unfortunately. Can you check that calling `(spaceline--segment-workspace-number)` manually returns nil?

**Comment by jwintz** [comment] 2016-03-14 20:07
How do can I do that ? It's not callable as it is not auto-loaded ...

Thanks for your concern :-)

**Comment by TheBB** [comment] 2016-03-14 20:08
Eval arbitrary lisp with `M-:`.

**Comment by jwintz** [comment] 2016-03-14 20:09
Here are the only choices I've got ...

<img width="743" alt="screen shot 2016-03-14 at 21 09 07" src="https://cloud.githubusercontent.com/assets/3277054/13758298/0f7c457a-ea29-11e5-9f2c-754fe0a6091c.png">

**Comment by TheBB** [comment] 2016-03-14 20:12
Again, it's a *function* so you have to start with a `(`. `M-:` evaluates lisp expressions so you have to write valid lisp.

**Comment by jwintz** [comment] 2016-03-14 20:18
I'm not proficient with emacs-lisp, yet. So I do not understand, sorry. How can I debug, either from my <code>init</code> file or interactively from within emacs ? Your way will be mine ;-)

**Comment by TheBB** [comment] 2016-03-14 20:19
`M-: (spaceline--segment-workspace-number)`

Does it return `nil` or not?

**Comment by TheBB** [comment] 2016-03-14 20:21
Also, can you check the value of `mode-line-format`? (`M-: mode-line-format`)

**Comment by jwintz** [comment] 2016-03-14 20:22
Here is what I've got:

<img width="744" alt="screen shot 2016-03-14 at 21 20 49" src="https://cloud.githubusercontent.com/assets/3277054/13758646/b5de5f38-ea2a-11e5-90f3-f7d7ad38e023.png">

So I guess it returns <code>nil</code>.

**Comment by TheBB** [comment] 2016-03-14 20:23
You're still trying to use it as a variable :-)

`M-: (spaceline--segment-workspace-number)`

Note the parentheses. You're doing this:

`M-: spaceline--segment-workspace-number`

**Comment by jwintz** [comment] 2016-03-14 20:25
Alright ! Thanks for your patience. I've got it now.

It returns <code>nil</code>.

**Comment by TheBB** [comment] 2016-03-14 20:25
Okay, then what about `mode-line-format`? That one is a variable.

**Comment by jwintz** [comment] 2016-03-14 20:28
Here's the only output I've got ...

<img width="740" alt="screen shot 2016-03-14 at 21 26 43" src="https://cloud.githubusercontent.com/assets/3277054/13758791/87cb3b10-ea2b-11e5-92a2-c0e7ddc992e7.png">

... which does not seem to be helpful :-/

**Comment by TheBB** [comment] 2016-03-14 20:29
That is helpful, actually. You have somehow got the mode-line stuff from window-numbering in there.

Probably you either enabled window-numbering *after* spaceline (so it interfered) or you didn't disable window-numbering's own mode-line features.

**Comment by jwintz** [comment] 2016-03-14 20:33
Arghhh. Too hard for me to understand. Here is my config:

<code>
(prolusion-require-package 'window-numbering)
(prolusion-install-package 'spacemacs-theme)
(prolusion-install-package 'spaceline)

[...]

(when (display-graphic-p)
  (load-theme 'spacemacs-dark t)
  (set-face-attribute 'mode-line nil :box nil)
  (setq ns-use-srgb-colorspace nil)
  (require 'spaceline-config)
  (setq powerline-default-separator 'wave)
  (setq spaceline-toggle-window-number-on t)
  (setq spaceline-toggle-workspace-number-on nil)
  (spaceline-spacemacs-theme)
  (spaceline-helm-mode +1))
</code>

where <code>prolusion-require-package</code> is:

<code>
(defun prolusion-require-package (package)
  ""
  (message "Loading package %s" package)
  (unless (package-installed-p package)
    (package-install package))
  (require package))
</code>

**Comment by TheBB** [comment] 2016-03-14 20:34
Just set up spaceline after you enable `window-numbering-mode` and you should be fine.

**Comment by jwintz** [comment] 2016-03-14 20:42
That solved the issue indeed ! Many thanks !

<img width="856" alt="screen shot 2016-03-14 at 21 41 07" src="https://cloud.githubusercontent.com/assets/3277054/13759220/88e4343c-ea2d-11e5-9963-0081bbf15a1f.png">

**Comment by jwintz** [comment] 2016-03-14 20:43
The key was explicitly to require:

<code>
(require 'window-numbering)
</code>

before:

<code>
(require 'spaceline-config)
</code>

**Comment by TheBB** [comment] 2016-03-14 20:46
Great! I'm closing this, then.

Hopefully I can add some tips to the readme about this kind of thing.

**Closed by TheBB** 2016-03-14 20:46 UTC

**Comment by jwintz** [comment] 2016-03-14 20:51
That's a great idea. As a confession, it would be great to add the NextStep hook, for MacOS users as well, cause it makes your package much prettier than the defaults. I had to dig a lot to find how how to make the separators look fine ...
