### ISSUE TITLE
Modeline awkwardly truncating/too long?

### ISSUE THREAD

**Issue by nickbclifford** [TheBB/spaceline#163] opened 2017-11-08 02:08 UTC
I just installed Spaceline and was trying to get my config working when I noticed that the line is truncating about one character too far/is one character too long.

![window](https://user-images.githubusercontent.com/11001606/32528194-55149688-c3f7-11e7-8b10-91b584c66f10.png)

You can kind of see the extra space in `-nw` mode:

![no window](https://user-images.githubusercontent.com/11001606/32528195-56e4b02e-c3f7-11e7-96a6-28db28cfdb9c.png)

How do I fix this? Is it something with the `mode-line-format`?

**Comment by deb0ch** [comment] 2017-11-08 08:13
Hahaha, I noticed that when implementing the responsiveness of the spaceline but couldn't come up with a fix at the time.

Can you tryout #161 to see if it fixes it ? 😸

**Comment by nickbclifford** [comment] 2017-11-08 21:53
@deb0ch Assuming that I'm applying the patch right, then no, it doesn't fix it.

**Comment by deb0ch** [comment] 2017-11-09 07:12
Then it might have something to do with a scrollbar, or the fringes, or the area for the continuation glyph or something like that, something that makes `window-width` not return the exact width of the window where you can actually insert characters (this is only my best guess).

Maybe the `PIXELWISE` argument of `window-width` has something to do with this 🤔 

Would you like to investigate on the cause ?

**Comment by nickbclifford** [comment] 2017-11-09 19:46
I'd love to help if I actually knew what was going on.

**Comment by deb0ch** [comment] 2017-11-11 12:00
Duplicate of #135

**Closed** 2018-03-20 09:08 UTC
Labels: duplicate
